version: '{build}'
skip_tags: true
# AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci]
#skip_commits:
#  message: /\[ci skip\]/
clone_depth: 10
environment:
  matrix:
    - ruby_version: '24'
    - ruby_version: '24-x64'
    - ruby_version: '23'
    - ruby_version: '23-x64'
    - ruby_version: '22'
    - ruby_version: '22-x64'
    - ruby_version: '22'
    - ruby_version: '22-x64'
    - ruby_version: '21'
    - ruby_version: '21-x64'
install:
  # Take default Ruby out of path
  - SET PATH=%PATH:C:\Ruby193\bin;=%
  # Add Ruby to path from build matrix
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  #- gem install bundler --force --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle
build_script:
  - bundle exec rake build
test_script:
  - bundle exec rake test:all
artifacts:
  - path: pkg\*.gem
